freelance/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('taskmanager.urls')),
    path('admin/', admin.site.urls),
]

taskmanager/urls.py
from django.urls import path
from . import views

app_name = 'taskmanager'

urlpatterns = [
    #path('homepage/', views.HomepageView.as_view(), name='homepage'),
    path('', views.index, name='index'),
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('home/', views.home, name='home'),
    path('profile/<username>', views.user_profile, name='profile'),
    path('post_project/', views.post_project, name='post_project'),
    path('myprojects/', views.myprojects, name='myprojects'),
	path('project_description/<int:project_id>/', views.project_description, name='project_description'),
    path('browse_jobs/', views.browse_jobs, name='browse_jobs'),
    path('<int:user_id>/jobForm/', views.jobForm, name='jobForm'),
    path('list/', views.list, name='list'),
    path('<int:user_id>/requestForm/', views.requestForm, name='requestForm'),
]

taskmanager/models.py
from django.db import models
from django.contrib.auth.models import User

import os

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, default=None)
    bio = models.TextField(max_length=500, default=None)
    gender = models.CharField(max_length=10, choices=(("Male", "Male"), ("Female", "Female")), default="Male", blank=False)
    def __str__(self):
        return self.user.username

    def delete(self, *args, **kwargs):
        os.remove(self.image.name)
        super(CustomUser, self).delete(*args, **kwargs)

class Project(models.Model):
    project_name = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=300, default=None)
    postedOn = models.DateTimeField(auto_now_add=True, blank=True)
    leader = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    #applicants = models.ManyToManyField(CustomUser)
    isCompleted = models.BooleanField(default=False)
    deadline = models.DateField(blank=False)
    def __str__(self):
        return self.project_name

taskmanager/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate, logout
from .models import Project, CustomUser
from datetime import datetime

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'homepage.html')
    else:
        return HttpResponseRedirect(reverse('taskmanager:home'))

def jobForm(request,user_id):
    return HttpResponse("You're looking at job form.")

def list(request):
    return HttpResponse("You're looking at list.")

def requestForm(request,user_id):
    return HttpResponse("You're looking at request form.")

def signup_user(request):
    context = dict()
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['password']
        first_name = request.POST['fname']
        last_name = request.POST['lname']
        email = request.POST['email']
        phone_number = request.POST['phno']
        bio = request.POST['bio']
        gender = request.POST['gender']
        user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name, email=email,)
        cuser = CustomUser(user=user, phone_number=phone_number, bio=bio, gender=gender)
        login(request, user)
        user.save()
        cuser.save()
        return HttpResponseRedirect(reverse("taskmanager:home"))
    return render(request, 'signup.html', context)

def login_user(request):
    if request.method == 'POST':
        context = dict()
        username = request.POST['name']
        password = request.POST['passwd']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if request.COOKIES.get('post_project'):
                return form_state(request, id=2)
            else:
                return HttpResponseRedirect(reverse('taskmanager:home'))
        else:
            if request.COOKIES.get('post_project'):
                context['post_project'] = 'post_project'
            context['error_message'] = 'Username or password is incorrect'
            return render(request, 'login.html', context)
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('taskmanager:index'))

def form_state(request, id=1):
    context = dict()
    if id == 1:
        project_name = request.POST['name']
        description = request.POST['desc']
        deadline = request.POST['deadline']
        context['post_project'] = 'post_project'
        response = render(request, 'login.html', context)
        response.set_cookie('post_project', 'post_project')
        response.set_cookie('name', str(project_name))
        response.set_cookie('desc', str(description))
        response.set_cookie('deadline', str(deadline))
        return response
    else:
        context['name'] = request.COOKIES.get('name')
        context['desc'] = request.COOKIES.get('desc')
        context['deadline'] = request.COOKIES.get('deadline')
        context['post_project'] = 'post_project'
        response = render(request, 'postproject.html', context)
        response.delete_cookie('post_project')
        response.delete_cookie('name')
        response.delete_cookie('desc')
        response.delete_cookie('deadline')
        return response

def post_project(request):
    if request.method == 'POST':
        project_name = request.POST['name']
        description = request.POST['desc']
        deadline = request.POST['deadline']
        if request.user.is_authenticated:
            project = Project()
            project.project_name = project_name
            project.description = description
            project.leader = CustomUser.objects.get(user=request.user.id)
            project.deadline = deadline
            project.postedOn=datetime.now()
            project.save()
            return redirect('taskmanager:project_description',project.id)
        else:
            return form_state(request)
    return render(request, "postproject.html")

def applicable_jobs(cuser):
    if not cuser:
        projects = Project.objects.all()
    else:
        projects = Project.objects.exclude(leader=cuser)

    jobs = set()
    if projects:
        for project in projects:
            if not project.isCompleted:
                jobs.add(project)
    if jobs:
        print(jobs)
        sorted(jobs, key=lambda x: x.postedOn, reverse=True)
    return jobs

def browse_jobs(request):
    context = dict()
    cuser = None
    if request.user.is_authenticated:
        cuser = CustomUser.objects.get(user=request.user)
    context['jobs'] = applicable_jobs(cuser)
    return render(request, 'browsejobs.html', context)


def home(request):
    if not request.user.is_superuser and request.user.is_authenticated:
        context = dict()
        cuser = CustomUser.objects.get(user=request.user)
        jobs_recommended = applicable_jobs(cuser)
        posted_projects = Project.objects.filter(
            leader=cuser).order_by('-postedOn')
        if len(posted_projects) == 0:
            context['posted_projects'] = None
        else:
            context['posted_projects'] = posted_projects
        context['jobs_recommended'] = jobs_recommended
        return render(request, 'dashboard.html', context)
    elif request.user.is_superuser:
        return redirect('/admin/')
    else:
        return HttpResponseRedirect(reverse('taskmanager:index'))


def project_description(request, project_id):
    project = Project.objects.get(id=project_id)
    if not project.isCompleted:
        if project.deadline < datetime.now().date():
            project.isCompleted = True
            project.save()
    context = dict()
    context['project'] = project
    context['project_id'] = project_id
    year = project.deadline.strftime("%Y")
    month = project.deadline.strftime("%m")
    date = project.deadline.strftime("%d")
    context['year'] = year
    context['month'] = month
    context['date'] = date
    if request.user.is_authenticated:
        context['is_leader'] = (project.leader.user == request.user)
    return render(request, 'projectdescription.html', context)

def user_profile(request, username):
    
    context = dict()
    user = User.objects.get(username=username)
    cuser = CustomUser.objects.get(user=user)
    context['cuser'] = cuser
    return render(request, 'profile.html', context)

def myprojects(request):
    if request.user.is_authenticated:
        context={}
        cuser=CustomUser.objects.get(user=request.user)
        posted_projects = Project.objects.filter(
            leader=cuser).order_by('-postedOn')
        context['posted_projects'] = posted_projects
        return render(request, 'myprojects.html',context)
    return render(request, 'login.html')

taskmanager/templates/browsejobs.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						{% if not request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
							<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						{% endif %}
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:profile' request.user.username %}">Profile</a></li>
							<li><a href="{% url 'taskmanager:myprojects' %}">My Projects</a></li>
							<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">Available jobs</h1>
							{% if error_message %}
							<b>{{error_message}}</b><br> 
							{% endif %}

							<!-- list of projects -->
							{% if jobs %}
							<ul class="jobs">
								{% for job in jobs %}
									<li><a href="{% url "taskmanager:project_description" job.id %}" ">{{ job.project_name}}</a></li>
								{% endfor %}
							</ul>
							{% endif %}
							<!-- end list of projects -->
						</div>
					</section>
			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

taskmanager/templates/dashboard.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						{% if not request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
							<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						{% endif %}
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:profile' request.user.username %}">Profile</a></li>
							<li><a href="{% url 'taskmanager:myprojects' %}">My Projects</a></li>
							<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">Your projects</h1>
							<!-- list of projects -->
							<div class="project">
								{% for project in posted_projects %}
									<a href="{% url "taskmanager:project_description" project.id %}" target="_blank">
										<h2>{{project.project_name}}</h2>
									</a>
									<p class="project-description">
										{{project.description}}
									</p>
								{% endfor %}
							</div>
							<!-- end list of projects -->
						</div>
					</section>

					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">Recommended projects</h1>
							<!-- list of projects -->
							<div class="project">
								{% for job in jobs_recommended %}
									<a href="{% url "taskmanager:project_description" job.id %}" target="_blank">
										<h2>{{job.project_name}}</h2>
									</a>
									<p class="project-description">
										{{job.description}}
									</p>
								{% endfor %}
							</div>
							<!-- end list of projects -->
						</div>
					</section>
			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

taskmanager/templates/home.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
						<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>

					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">A Place for Professionals</h1>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
						</div>
					</section>

			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

taskmanager/templates/myprojects.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						{% if not request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
							<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						{% endif %}
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:profile' request.user.username %}">Profile</a></li>
							<li><a href="{% url 'taskmanager:myprojects' %}">My Projects</a></li>
							<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">Posted projects</h1>
							<!-- list of projects -->
							<div class="project">
								{% for project in posted_projects %}
									<a href="{% url "taskmanager:project_description" project.id %}" target="_blank">
										<h2>{{project.project_name}}</h2>
									</a>
									<p class="project-description">
										{{project.description}}
									</p>
								{% endfor %}
							</div>
							<!-- end list of projects -->
						</div>
					</section>
			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

taskmanager/templates/profile.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						{% if not request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
							<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						{% endif %}
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:profile' request.user.username %}">Profile</a></li>
							<li><a href="{% url 'taskmanager:myprojects' %}">My Projects</a></li>
							<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">{{cuser.user.username}}</h1>
							<!-- list of projects -->
							<div class="bio">
								<h2>Description</h2>
								<p class="project-description">
									{{cuser.bio}}
								</p>
							</div>
							<!-- end list of projects -->
						</div>
					</section>

					<section id="main" class="wrapper">
						<div class="inner">
							<hr/>
							<!-- list of projects -->
							<div class="project">
								<b>User Id </b>{{cuser.user.id}}<br>
								<b>Email </b>{{cuser.user.email}}<br>
								<b>Phone No. </b>{{cuser.phone_number}}<br>
							</div>
							<!-- end list of projects -->
						</div>
					</section>
			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

taskmanager/templates/projectdescription.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<title>Freelancer Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css" %}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href={% url "taskmanager:index" %} class="title">Freelancer Website</a>
				<nav>
					<ul>
						<li><a href="{% url 'taskmanager:index' %}" class="active">Home</a></li>
						{% if not request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
							<li><a href="{% url 'taskmanager:signup' %}">Signup</a></li>
						{% endif %}
						<li><a href="{% url 'taskmanager:post_project' %}">Post a Project</a></li>
						<li><a href="{% url 'taskmanager:browse_jobs' %}">Browse Jobs</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'taskmanager:profile' request.user.username %}">Profile</a></li>
							<li><a href="{% url 'taskmanager:myprojects' %}">My Projects</a></li>
							<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">{{project.project_name}}</h1>
							{% if error_message %}
							<b>{{error_message}}</b><br> 
							{% endif %}
							<h3>Project description:</h3>
							<p>{{project.description}}</p>
							<hr />
							<p>
								<b>Posted On: {{project.postedOn}}</b>
								<i>Deadline: {{project.deadline}}</i>
							</p>
							{% if not request.user.is_authenticated %}
								<i>Login then you can apply.</i>
							{% endif %}
							{% if request.user.is_authenticated and not is_leader %}
								<a href="#" class="button primary icon solid">Apply</a>
							{% endif %}
						</div>
					</section>
			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; All rights reserved for Freelance.</li><li>Design: <a href="#">Hamed Bahrami</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrollex.min.js" %}"></script>
			<script src="{% static "assets/js/jquery.scrolly.min.js" %}" ></script>
			<script src="{% static "assets/js/browser.min.js" %}" ></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}" ></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>